bugfix: require force to overwrite existing AData
fixes #98
new behaviour: both, method call to store_adata if option Force is not set
as well as direct attribute access to create adata fails
with AttributeError:

   scn.adata['testoverwrite']=sarpy.AData.fromdata(scn.pdata[0], data=numpy.eye(40))
   ...
   AttributeError: AData (key="testoverwrite") exists
   To force overwrite, use store_adata with option force=True
   scn.store_adata(key='testoverwrite', data=numpy.eye(40))
   ...
   AttributeError: AData (key="testoverwrite") exists
   To force overwrite, use store_adata with option force=True

To do it, issue:

   scn.store_adata(key='testoverwrite', data=numpy.eye(40), force=True)
   assigning testoverwrite ...