major changes to analysis and wrappers. fixi-fying many things.
roi enhancement curves are ALMOST working. There is a slight problem still though:

for items in adv_analyze_list:

    if items[1] == 'ec':

        sarpy.fmoosvi.wrappers.calc_enhancement_curve(masterlist,
                                                      items[0],items[1],
                                                      items[2],forceVal=fFlag)

<sarpy.io.BRUKER_classes.PDATA_file object at 0x10a63da10>
Perhaps you didn't pass in a valid mask or passed bad data
Traceback (most recent call last):

  File "<ipython-input-202-bd53bb387d88>", line 8, in <module>
    items[2],forceVal=fFlag)

  File "/phd/Dropbox/code/python/sarpy/fmoosvi/wrappers.py", line 261, in calc_enhancement_curve
    conc = sarpy.fmoosvi.analysis.h_enhancement_curve(scan, roi_label)

  File "/phd/Dropbox/code/python/sarpy/fmoosvi/analysis.py", line 156, in h_enhancement_curve
    new_scan_object.pdata[pdata_num].data = norm_data

  File "/phd/Dropbox/code/python/sarpy/ImageProcessing/resample_onto.py", line 134, in resample_onto_pdata
    header = visu_pars_2_Nifti1Header(source_pdata.visu_pars)

AttributeError: 'str' object has no attribute 'visu_pars'